spring:
    port: 8080
    application:
        name: telegram
        controllers:
            telegram:
                base-path: /telegram
telegram:
    bot:
        chat_id: 5043127453
        token: "8440529033:AAED6z0-9shdo5uQ5hfr22Nzt7Ai7vMLWoo"
        resource: /bot
        operations:
            sendMessage: /sendMessage
            deleteWebhook: /deleteWebhook
            setWebhook: /setWebhook
    url: https://api.telegram.org
ngrok:
    api: http://localhost:4040/api/tunnels